url: https://blissfulrepair.github.io
baseurl: / 

# Site settings
title: Blissful Repair
email: dalton@blissfulrepair.com 
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Dalton Bliss
  pic: 1
  position: Owner/Lead Repair Technician
  social:
    - title: facebook
      url: https://facebook.com/blissfulrepair

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/blissfulrepair

# Postal address (add as many lines as necessary)
address: 
  - line: Longmont, CO, 80501

# reviews
reviews:
  - review1: August 11, 2019
    text: Killer warranty, came to me on my schedule and was very flexible and honest with prices. Thanks guys!
  - review2: July 16, 2019
    text: Great tech, does a good job with delicate repairs.
  - review3: July 16, 2019
    text: The convenience of him coming to you is a major plus.
# Build settings
markdown: kramdown
permalink: pretty
